# Generated by Django 4.2.11 on 2026-03-01 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID da transação"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("authorized", "Autorizado"),
                            ("captured", "Capturado"),
                            ("denied", "Negado"),
                            ("refunded", "Estornado"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor"
                    ),
                ),
                (
                    "card_last_four",
                    models.CharField(max_length=4, verbose_name="últimos 4 dígitos"),
                ),
                (
                    "authorization_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="código de autorização"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="orders.order",
                        verbose_name="pedido",
                    ),
                ),
            ],
            options={
                "verbose_name": "pagamento",
                "verbose_name_plural": "pagamentos",
            },
        ),
    ]
